[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "dn404/=lib/dn404/src/",
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "@openzeppelin/foundry-upgradeable/=lib/openzeppelin-foundry-upgradeable/",
  "solady/=lib/dn404/lib/solady/src"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
