[profile.default]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "dn404/=lib/dn404/src/",
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "openzeppelin-foundry-upgrades/=lib/openzeppelin-foundry-upgrades/src/",
  "solady/=lib/dn404/lib/solady/src",
  "@layerzerolabs/lz-evm-oapp-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/oapp/",
  "@layerzerolabs/lz-evm-protocol-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/protocol/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
