[profile.default]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "dn404/=lib/dn404/src/",
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "openzeppelin-foundry-upgrades/=lib/openzeppelin-foundry-upgrades/src/",
  "solady/=lib/dn404/lib/solady/src"
]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
multiline_func_header = "params_first"
line_length = 105

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
